apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-default-backend-ee85e06
  namespace: osm-system
spec:
  selector:
    matchLabels:
      app: osm-default-backend-ee85e06
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: osm-default-backend-ee85e06
    spec:
      containers:
      - name: osm-default-backend-ee85e06
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: osm-default-backend-ee85e06-svc
  namespace: osm-system
  labels:
    version: "1.0"
spec:
  selector:
    app: osm-default-backend-ee85e06
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP