apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: todo
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://bjd145.azurecr.io/helm
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: todo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: b2c-todo
      version: '0.1.4'
      sourceRef:
        kind: HelmRepository
        name: todo
        namespace: flux-system
      interval: 10m
  values:
    hostname: 'todo.bjdazure.tech'
    todo_build_version: 'ab34b340dc9297d2312115c2375b99d998f6fa77'