apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin-sa-identity
  namespace: otel-system
  annotations:
    azure.workload.identity/client-id: default_zipkin_client_id
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"