apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: otel-collector-config
  namespace: otel-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: k8994a-kv
    clientID: default_zipkin_client_id
    cloudName: ""                                     
    objects:  |
      array:
        - |
          objectName: otel-collector-config
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
---