---
apiVersion: v1
kind: Namespace
metadata:
  name: kubecost-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubecost
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubecost.github.io/cost-analyzer/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost-release
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kubecost-system
  chart:
    spec:
      chart: cost-analyzer
      version: '1.101.3'
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: flux-system
      interval: 1m