---
apiVersion: v1
kind: Namespace
metadata:
  name: kured-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubereboot.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured-release
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kured-system
  chart:
    spec:
      chart: kured
      version: '4.0.2'
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
      interval: 1m
  values:
    nodeSelector:
      kubernetes.io/os: linux