apiVersion: apiserver.config.k8s.io/v1 
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "privileged"
      enforce-version: "latest"
      audit: "privileged"
      audit-version: "latest"
      warn: "privileged"
      warn-version: "latest"
    exemptions:
      namespaces: ["kube-system", "kured-system", "kubecost-system", "otel-system", "dapr-system", "knative-serving", "aks-istio-gateways", "aks-istio-system"]