apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  namespace: osm-system
  name: osm-mesh-config
spec:
  traffic:
    enableEgress: true
    useHTTPSIngress: true
    enablePermissiveTrafficPolicyMode: true
  observability:
    enableDebugServer: true
    tracing:
      enable: false