---
apiVersion: v1
kind: Namespace
metadata:
  name: contour-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m0s
  url:  https://charts.bitnami.com/bitnami 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour-system
spec:
  interval: 5m
  chart:
    spec:
      chart: contour
      version: '1.19.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m