apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: bookstore-tls-proxy
  namespace: bookstore
spec:
  virtualhost:
    fqdn: bookstore.bjdazure.tech
    tls:
      secretName: bookstore-ingress-tls
  routes:
  - services:
    - name: bookstore
      port: 14001
---
kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: bookstore-backend
  namespace: bookstore
spec:
  backends:
  - name: bookstore
    port:
      number: 14001
      protocol: http
  sources:
  - kind: Service
    namespace: osm-system
    name: osm-contour-envoy