apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: bookstore-tls
  namespace: bookstore
spec:
  provider: azure
  secretObjects:                               
  - secretName: bookstore-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-bjdazure-tech
      key: tls.key
    - objectName: wildcard-bjdazure-tech
      key: tls.crt
  parameters:
    usePodIdentity: "true"                                        
    keyvaultName: f1dd32-kv                                                        
    objects:  |
      array:
        - |
          objectName: wildcard-bjdazure-tech
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
---