---
apiVersion: v1
kind: Namespace
metadata:
  name: keda-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda-system
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: '2.5.0'
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      interval: 1m