---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-workload-identity-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: azure-workload-identity
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://azure.github.io/azure-workload-identity/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-workload-identity
  namespace: azure-workload-identity-system
spec:
  interval: 5m
  chart:
    spec:
      chart: workload-identity-webhook
      version: '0.8.0'
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: flux-system
      interval: 1m
  values:
    azureTenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47