kind: ConfigMap
apiVersion: v1
metadata:
  name:  istio-shared-configmap-asm-1-17
  namespace: aks-istio-system
data:
  mesh: |-
    defaultConfig:
      tracing:
        zipkin:
          address: otel-collector.otel-system.svc.cluster.local:9411
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY

  meshNetworks: 'networks: {}'