---
apiVersion: v1
kind: Namespace
metadata:
  name: kured-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kured
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://weaveworks.github.io/kured
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: '2.10.0'
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
      interval: 1m
  values:
    nodeSelector:
      kubernetes.io/os: linux
    