---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dapr
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://dapr.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 5m
  chart:
    spec:
      chart: dapr
      version: '1.8.3'
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
      interval: 1m
  values:
    global.mtls.enabled: false
    global.logAsJson: true
    global.ha.enabled: false
