---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: httpbin-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/httpbin
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-flux-extension
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bookstore-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/bookstore
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-flux-extension
  validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: eshopondapr
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   sourceRef:
#     kind: GitRepository
#     name: aks-flux-extension
#   path: ./apps/eShopOnDapr
#   prune: true
#   validation: client