#Don't forget: 
#  kubectl get ns | grep -i book | awk '{print $1}' | xargs osm namespace add
#  kubectl get ns | grep -i book | awk '{print $1}' | xargs -I {} kubectl -n {} rollout restart deployment {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookbuyer
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookthief
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookwarehouse
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled
---