apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale
  namespace: knative-example
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
      - image: bjd145/whatos:2.0
        ports:
        - name: http8081
          containerPort: 8081
