trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - application/*
    - infrastructure/*

variables:
  STORAGE_ACCOUNT:    ""
  PLAN_FILE:          "aks.production.plan.${today}-${uuid}"              
  AKS_RG_NAME:        "DevSub_K8S_RG"
  ACR_NAME:           ""

stages:
- stage: build
  jobs: 
  - job: 'Publish_Files'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: infrastructure
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
   
- stage: deploy
  jobs:
  - deployment: 'Build_AKS'
    pool:
      vmImage: 'Ubuntu 18.04'
    environment: 'AKS'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.ArtifactsDirectory)/'
            displayName: Get Artifacts 

          - bash: |
              today=`date +"%y%m%d"`
              uuid=`uuidgen | sed 's/-//g'`

              export ARM_CLIENT_ID="$(client_id)"
              export ARM_CLIENT_SECRET="$(client_secret)"
              export ARM_SUBSCRIPTION_ID="$(subscription_id)"
              export ARM_TENANT_ID="$(tenant_id)"

              cd '$(System.ArtifactsDirectory)/drop'

              az extension add --name aks-preview
              az extension update --name aks-preview

              az login --service-principal -u ${ARM_CLIENT_ID} -p ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
              az account set -s ${ARM_SUBSCRIPTION_ID}

              wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
              unzip terraform_1.0.5_linux_amd64.zip
              
              ./terraform init -backend=true -backend-config="access_key=$(access_key)" -backend-config="key=sandbox.terraform.tfstate"
              ./terraform plan -out="$(PLAN_FILE)" -var "resource_group_name=$(AKS_RG_NAME)" -var-file="sandbox.tfvars"
              ./terraform apply -auto-approve $(PLAN_FILE)

              az storage copy --source-local-path "./$(PLAN_FILE)" --destination-account-name $(STORAGE_ACCOUNT) --destination-container plans
            displayName: Build Cluster     