apiVersion: v1
kind: Namespace
metadata:
  name: traduire
  labels:
    istio-injection: enabled
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "app", "operator": "Equal", "effect": "NoSchedule", "value": "traduire"}]'
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traduire-40ec6a81
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjd145.azurecr.io/helm/v1/repo/
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traduire-5343
  namespace: traduire
spec:
  interval: 5m
  chart:
    spec:
      chart: traduire
      version: '1.5.7'
      sourceRef:
        kind: HelmRepository
        name: traduire-40ec6a81
        namespace: flux-system
      interval: 1m
