apiVersion: v1
kind: Namespace
metadata:
  name: eshopondapr
  labels:
    istio.io/rev: asm-1-17
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "reservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "eShopOnDapr"}]'
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eshopondapr
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://bjdcsa.azurecr.io/helm
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:  eshopondapr-201
  namespace: eshopondapr
spec:
  interval: 5m
  chart:
    spec:
      chart: eshopondapr
      version: '2.0.2'
      sourceRef:
        kind: HelmRepository
        name:  eshopondapr
        namespace: flux-system
      interval: 1m
  values:
    gatewayDnsNameOrIP: eshop-api.bjdazure.tech
    identityDnsNameOrIP: identity-api.bjdazure.tech
    blazorDnsNameOrIP: shop.bjdazure.tech
    istio_gateway: istio-gateways/default-bjdazure-tech-gw