---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    enablePrometheusMerge: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    tracing:
      sampling: 60
      zipkin:
        address: otel-collector.default.svc.cluster.local:9411
  values:
    global:
      tracer:
        zipkin:
          address: otel-collector.default.svc.cluster.local:9411 
  components:
    egressGateways:
    - name: istio-egressgateway
      namespace: default
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        namespace: default
        enabled: true
        label:
          aadpodidbinding: bjdk8s03uat-ingress-identity
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  addonComponents:
    prometheus:
      enabled: false
    kiali:
      enabled: false
    grafana:
      enabled: false