apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: app-81e86b
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjd145.azurecr.io/helm/v1/repo/
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-81e86b
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sentimentchat
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: app-81e86b
        namespace: flux-system
      interval: 1m
  values:
    keyvault_name: 'bjdk8s04uat-kv'
    certificate_name: 'wildcard-bjdazure-tech'
    pod_identity: 'bjdk8s04uat-ingress-identity'
    tenant_id: '72f988bf-86f1-41af-91ab-2d7cd011db47'
    hostname: 'csi.bjdazure.tech'
