apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: app-81e86b
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjd145.azurecr.io/helm/v1/repo/
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cognitive-services
spec:
  hosts:
  - centralus.api.cognitive.microsoft.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-81e86b
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sentimentchat
      version: '0.2.4'
      sourceRef:
        kind: HelmRepository
        name: app-81e86b
        namespace: flux-system
      interval: 1m
  values:
    keyvault_name: 'app-81e86b-kv'
    keyvault_secret_name: 'app-81e86b-cogs-key'
    pod_identity: 'app-81e86b-identity'
    hostname: 'chat.bjdazure.tech'
    tenant_id: '72f988bf-86f1-41af-91ab-2d7cd011db47'