apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: todo-da27d5
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjd145.azurecr.io/helm/v1/repo/
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: todo-da27d5
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: b2c-todo
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: todo-da27d5
        namespace: flux-system
      interval: 1m
  values:
    hostname: 'todo.bjdazure.tech'
    todo_build_version: '054c066116570b6d3051b894915ca31dd491c31d'
