apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: todo-da27d5
  namespace: flux-system
spec:
  interval: 1m
  url: https://bjd145.azurecr.io/helm/v1/repo/
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: todo-da27d5
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: b2c-todo
      version: '0.1.4'
      sourceRef:
        kind: HelmRepository
        name: todo-da27d5
        namespace: flux-system
      interval: 1m
  values:
    hostname: 'todo.bjdazure.tech'
    todo_build_version: 'ab34b340dc9297d2312115c2375b99d998f6fa77'
