---
apiVersion: v1
kind: Namespace
metadata:
  name: osm-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: osm
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://openservicemesh.github.io/osm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osm
  namespace: osm-system
spec:
  interval: 5m
  chart:
    spec:
      chart: osm
      version: '0.11.1'
      sourceRef:
        kind: HelmRepository
        name: osm
        namespace: flux-system
      interval: 1m
  values:
    contour:
      enabled: true
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Service
            apiVersion: v1
            metadata:
              name: osm-contour-envoy
              namespace: osm-system
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "true"