name: Creates K8s without a Mesh installed
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'The name of the cluster to create - e616aq|f1dd32'
        required: true
        default: 'e616aq'
     
jobs:
  deploy:
    name: Deploy Cluster
    runs-on: self-hosted
    env:
      ARM_USE_MSI: true 
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      CORE_SUBSCRIPTION_ID: ${{ secrets.CORE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_SUBSCRIPTION_ID: ${{ secrets.ACR_SUBSCRIPTION_ID }}
      SERVICE_TYPE_MESH: none
      CLUSTER_RG:  DevSub02_K8S_${{ github.event.inputs.cluster_name }}_RG
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
      GITHUB_ACCOUNT: briandenicola
      GITHUB_REPO: kubernetes-cluster-setup
      REPO_BRANCH: master

    defaults:
      run:
        working-directory: './infrastructure'

    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: Login to Azure
      run: |
        az login --identity 

    - name: "Terraform Setup"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform Init"
      id: init
      run: terraform init -backend=true -backend-config="tenant_id=${{ env.ARM_TENANT_ID }}" -backend-config="subscription_id=${{ env.CORE_SUBSCRIPTION_ID }}" -backend-config="key=${{ env.CLUSTER_NAME }}.terraform.tfstate"
      
    - name: "Terraform Plan"
      id: plan
      run:  terraform plan -out="${{ env.CLUSTER_NAME }}.plan" -var "cluster_name=${{ env.CLUSTER_NAME }}" -var "resource_group_name=${{ env.CLUSTER_RG }}" -var "certificate_base64_encoded=${{ secrets.CERTIFICATE }}"  -var "certificate_password=${{ secrets.CERT_PASSWORD }}" -var "service_mesh_type=none" -var-file="k8s.tfvars"
      continue-on-error: false 

    - name: "Terraform Apply"
      id: apply
      run: terraform apply -auto-approve ${{ env.CLUSTER_NAME }}.plan