name: Creates K8s with a Mesh installed
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'The name of the cluster to create - e416aa|f1dd32'
        required: true
        default: 'e416aa'
      mesh_type:
        description: 'Type of service mesh to include in the cluster - istio|osm'
        required: true
        default: 'istio'
      
jobs:
  deploy:
    name: Deploy Cluster
    runs-on: self-hosted
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        STORAGE_ACCESS_KEY: ${{ secrets.storage_access_key }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        ACR_NAME: ${{ secrets.ACR_NAME }}
        ACR_SUBSCRIPTION_ID: ${{ secrets.ACR_SUBSCRIPTION_ID }}
        SERVICE_TYPE_MESH:  ${{ github.event.inputs.mesh_type }}
        CLUSTER_RG:  DevSub02_K8S_${{ github.event.inputs.mesh_type }}
        CLUSTER_NAME: ${{ github.event.inputs.cluster_name}}
        GITHUB_ACCOUNT: briandenicola
        GITHUB_REPO: kubernetes-cluster-setup
        REPO_BRANCH: master

    defaults:
      run:
        working-directory: './infrastructure'

    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Log into Azure"
      uses: Azure/login@v1.1
      with:
        creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

    - name: "Terraform Setup"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform Init"
      id: init
      run: terraform init -backend=true -backend-config="access_key=${{ env.STORAGE_ACCESS_KEY }}" -backend-config="key=${{ env.SERVICE_TYPE_MESH }}.terraform.tfstate"
      
    - name: "Terraform Plan"
      id: plan
      run:  terraform plan -out="${{ env.SERVICE_TYPE_MESH }}.plan" -var "resource_group_name=${{ env.CLUSTER_RG }}" -var "certificate_base64_encoded=${{ secrets.CERTIFICATE }}"  -var "certificate_password=${{ secrets.CERT_PASSWORD }}" -var "service_mesh_type=${{ env.SERVICE_TYPE_MESH }}" -var-file="${{ env.SERVICE_TYPE_MESH }}.tfvars"
      continue-on-error: false 

    - name: "Terraform Apply"
      id: apply
      run: terraform apply -auto-approve ${{ env.SERVICE_TYPE_MESH }}.plan
    
    - name: Setup Flux
      run: |
        export CLUSTER_BOOTSTRAP_PATH=./cluster-manifests/${{ env.SERVICE_TYPE_MESH }}
        chmod a+x ./aks-flux-configuration.sh
        ./aks-flux-configuration.sh
