name: Test Action
on:
  workflow_dispatch:
    inputs:
      mesh_type:
        description: 'Type of service mesh to include in the cluster'
        required: true
        default: 'osm'

jobs:
  deploy:
    name: Deploy Cluster
    runs-on: self-hosted
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        STORAGE_ACCESS_KEY: ${{ secrets.storage_access_key }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        ACR_NAME: ${{ secrets.ACR_NAME }}
        ACR_SUBSCRIPTION_ID: ${{ secrets.ACR_SUBSCRIPTION_ID }}
        SERVICE_TYPE_MESH:  ${{ github.event.inputs.mesh_type }}"
        CLUSTER_RG: DevSub02_K8S_${{env.SERVICE_TYPE_MESH}}_RG
        CLUSTER_NAME: bjdk8s-${{env.SERVICE_TYPE_MESH}}_RG
        GITHUB_ACCOUNT: briandenicola
        GITHUB_REPO: kubernetes-cluster-setup
        REPO_BRANCH: master

    defaults:
      run:
        working-directory: './infrastructure'

    steps:
    - name: "Checkout"
      uses: actions/checkout@master
    
    - name: Echo Test
      run: |
        echo ${{ env.SERVICE_TYPE_MESH }}
        echo ${{ env.CLUSTER_RG }}
        echo ${{ env.CLUSTER_NAME }}