name: Test String concat in Actions
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'The name of the cluster to create - e416aa|f1dd32'
        required: true
        default: 'e416aa'
      
jobs:
  deploy:
    name: Deploy Cluster
    runs-on: self-hosted

    defaults:
      run:
        working-directory: './infrastructure'

    steps:
    - name: Setup Flux
      run: |
        export IDENTITY_NAME="${{ github.event.inputs.cluster_name }}-identity"
        export IDENTITY_RG="DevSub02_${{ github.event.inputs.cluster_name }}_RG"

        echo ${IDENTITY_RG}
        echo ${IDENTITY_NAME}