apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: chat
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://bjdcsa.azurecr.io/helm
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chat-033
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sentimentchat
      version: '0.3.3'
      sourceRef:
        kind: HelmRepository
        name: chat
        namespace: flux-system
      interval: 1m
  values:
    chat_image_version: '9c73d9f2fcb02a3f7fe8daa7707d0819269a6eef'
    keyvault_name: 'chat-e0ce7b6-kv'
    keyvault_secret_name: 'chat-e0ce7b6-cogs-key'
    pod_identity: 'chat-e0ce7b6-identity'
    hostname: 'chat.bjdazure.tech'
    tenant_id: '72f988bf-86f1-41af-91ab-2d7cd011db47'